'use client'
import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Lang = 'en' | 'hi'

/* ── Translations ─────────────────────────────── */
export const T = {
  en: {
    greeting_morning:   'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening:   'Good evening',
    today_money:        "Today's Money",
    this_week:          'This week',
    go_online:          'Start Working — Go Online',
    you_are_online:     'You are online. Jobs can find you now.',
    jobs_near_you:      'Jobs Near You',
    see_all:            'See all',
    view_apply:         'View details & Apply',
    filters:            ['All','Today','Tomorrow','Near Me','High Pay'],
    you_earn:           'you earn',
    spots_left:         (n:number) => `${n} spot${n!==1?'s':''} left`,
    urgent:             '⚡ Urgent',
    apply_btn:          'Apply for This Job →',
    applied_btn:        'Done! You applied',
    home:               'Home',
    browse:             'Browse',
    shifts:             'Shifts',
    earnings:           'Earnings',
    profile:            'Profile',
    total_earned:       'Total Earned (This Month)',
    in_your_bank:       'In your bank',
    on_the_way:         'On the way',
    this_week_lbl:      'This Week',
    payment_history:    'Payment History',
    paid_lbl:           '✓ Paid',
    processing_lbl:     '⏳ Processing',
    my_shifts:          'My Shifts',
    upcoming:           '📅 Upcoming',
    past_shifts:        '✅ Past',
    my_availability:    'My Availability',
    tap_to_show:        'Tap to show when you can work',
    avail_set:          (n:number) => `${n} slots set`,
    available:          'Available',
    not_available:      'Not available',
    settings:           'Settings',
    notifications_lbl:  'Notifications',
    all_lbl:            'All',
    unread_lbl:         'Unread',
    no_notifs:          'No notifications yet',
    confirm_job_ttl:    'Job Accepted!',
    confirm_job_sub:    'Well done! Your shift is confirmed.',
    get_directions:     'Get Directions',
    tell_friend:        'Tell a Friend',
    back_to_jobs:       'Back to Jobs',
    slide_to_accept:    'Slide to accept →',
    urgent_nearby:      'URGENT NEARBY',
    urgent_headline:    'Employer needs someone right now — within 1 hour',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} from you · Only ${n} spot${n!==1?'s':''} left`,
    accept_job:         'Accept This Job',
    accept_job_sub:     'View full details before confirming',
    not_interested:     'Not interested',
    enter_arrival_otp:  'Enter Arrival OTP',
    ask_employer_otp:   'Ask your employer for the 4-digit code',
    starts_shift_timer: 'This starts your shift timer',
    confirm_arrival:    'Confirm Arrival',
    shift_in_progress:  'Shift in progress',
    earned_so_far:      'Earned so far',
    slide_to_end:       'Slide to End Shift',
    slide_to_end_sub:   'Slide to mark shift as complete',
    shift_ended:        'Shift Ended!',
    accepted_lbl:       'Accepted!',
    active_shift:       'Active Shift',
    confirm_arrival_ttl:'Confirm Arrival',
    wrong_otp:          'Wrong OTP — try again',
    demo_otp:           'Demo OTP:',
    job_details:        'Job Details',
    what_to_bring:      'What to Bring',
    money_note:         'Money paid directly to your account after the shift',
    you_will_earn:      'You will earn',
    what_bring_items:   ['Valid ID card','Comfortable shoes','Water bottle','Your phone'],
    skills_title:       'My Skills',
    skills_sub:         'Select what kind of work you can do',
    edit_info:          'Edit Info',
    work_area:          'Work Area',
    languages_speak:    'Languages I Speak',
    save_changes:       'Save Changes',
    search_placeholder: 'Search jobs, companies...',
    no_jobs_found:      'No jobs found',
    no_jobs_sub:        'Try a different search or category',
    rate_job:           '⭐ Rate this job',
    confirmed:          'Confirmed',
    pending:            'Pending',
    completed:          'Completed',
    jobs_done:          'Jobs done',
    your_rating:        'Your rating',
    money_coming:       'Money coming',
    results:            'Results',
    all_jobs:           'All Jobs',
    date_when:          'When',
    duration:           'Duration',
    pay_lbl:            'Pay',
    distance:           'Distance',
    slots:              'Slots',
    rating:             'Rating',
    onb1_title:         'Find Work Near You',
    onb1_sub:           'See verified jobs within 5 km of your home. Choose shifts that fit your time.',
    onb2_title:         'Earn ₹99–₹129 Per Hour',
    onb2_sub:           'Fixed hourly rates. No agent cuts. No hidden fees. What you see is what you get.',
    onb3_title:         'Get Paid the Same Day',
    onb3_sub:           'Money goes straight to your bank account after every shift. No waiting.',
    onb4_title:         'Safe & Verified Jobs Only',
    onb4_sub:           'Every employer is checked. Every job is real. Your Aadhaar keeps you safe.',
    get_started:        'Get Started →',
    already_account:    'Already have an account? Login',
    login_title:        'Welcome back',
    login_sub:          'Enter your phone number to continue',
    phone_label:        'Phone Number',
    phone_placeholder:  'Enter 10-digit mobile number',
    password_label:     'Password',
    password_placeholder:'Enter your password',
    login_btn:          'Login',
    no_account:         "Don't have an account? Register",
    register_title:     'Create Account',
    register_sub:       'Join thousands of workers earning daily',
    name_label:         'Full Name',
    name_placeholder:   'Enter your full name',
    city_label:         'Your City',
    city_placeholder:   'e.g. Mumbai, Delhi, Bangalore',
    lang_label:         'App Language',
    register_btn:       'Create Account',
    have_account:       'Already have an account? Login',
  },

  hi: {
    greeting_morning:   'सुप्रभात',
    greeting_afternoon: 'नमस्कार',
    greeting_evening:   'शुभ संध्या',
    today_money:        'आज की कमाई',
    this_week:          'इस हफ़्ते',
    go_online:          'काम शुरू करें — ऑनलाइन हों',
    you_are_online:     'आप ऑनलाइन हैं। अब नौकरी मिल सकती है।',
    jobs_near_you:      'आपके पास की नौकरियाँ',
    see_all:            'सब देखें',
    view_apply:         'विवरण देखें और आवेदन करें',
    filters:            ['सब','आज','कल','पास में','अधिक वेतन'],
    you_earn:           'आपको मिलेगा',
    spots_left:         (n:number) => `${n} जगह बची`,
    urgent:             '⚡ तुरंत चाहिए',
    apply_btn:          'इस काम के लिए आवेदन करें →',
    applied_btn:        'हो गया! आवेदन हो गया',
    home:               'होम',
    browse:             'ढूंढें',
    shifts:             'शिफ़्ट',
    earnings:           'कमाई',
    profile:            'प्रोफ़ाइल',
    total_earned:       'कुल कमाई (इस महीने)',
    in_your_bank:       'आपके बैंक में',
    on_the_way:         'आने वाला है',
    this_week_lbl:      'इस हफ़्ते',
    payment_history:    'भुगतान इतिहास',
    paid_lbl:           '✓ मिल गया',
    processing_lbl:     '⏳ आ रहा है',
    my_shifts:          'मेरी शिफ़्ट',
    upcoming:           '📅 आने वाली',
    past_shifts:        '✅ गुज़री हुई',
    my_availability:    'मेरी उपलब्धता',
    tap_to_show:        'टैप करें कि कब काम कर सकते हैं',
    avail_set:          (n:number) => `${n} स्लॉट सेट`,
    available:          'उपलब्ध',
    not_available:      'उपलब्ध नहीं',
    settings:           'सेटिंग्स',
    notifications_lbl:  'सूचनाएँ',
    all_lbl:            'सब',
    unread_lbl:         'नहीं पढ़ा',
    no_notifs:          'अभी कोई सूचना नहीं',
    confirm_job_ttl:    'नौकरी मिल गई!',
    confirm_job_sub:    'बहुत अच्छा! आपकी शिफ़्ट पक्की हो गई।',
    get_directions:     'रास्ता देखें',
    tell_friend:        'दोस्त को बताएँ',
    back_to_jobs:       'वापस नौकरियों पर',
    slide_to_accept:    'स्वीकार करने के लिए स्लाइड करें →',
    urgent_nearby:      'तुरंत पास में',
    urgent_headline:    'नियोक्ता को अभी किसी की ज़रूरत है — 1 घंटे में',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} दूर · सिर्फ ${n} जगह बची`,
    accept_job:         'यह काम स्वीकार करें',
    accept_job_sub:     'पुष्टि से पहले पूरा विवरण देखें',
    not_interested:     'रुचि नहीं',
    enter_arrival_otp:  'आगमन OTP दर्ज करें',
    ask_employer_otp:   'नियोक्ता से 4-अंकों का कोड लें',
    starts_shift_timer: 'यह आपकी शिफ़्ट टाइमर शुरू करेगा',
    confirm_arrival:    'आगमन पुष्टि करें',
    shift_in_progress:  'शिफ़्ट चल रही है',
    earned_so_far:      'अब तक की कमाई',
    slide_to_end:       'शिफ़्ट समाप्त करने के लिए स्लाइड करें',
    slide_to_end_sub:   'शिफ़्ट पूरी करने के लिए स्लाइड करें',
    shift_ended:        'शिफ़्ट खत्म!',
    accepted_lbl:       'स्वीकृत!',
    active_shift:       'चालू शिफ़्ट',
    confirm_arrival_ttl:'आगमन पुष्टि',
    wrong_otp:          'गलत OTP — फिर से कोशिश करें',
    demo_otp:           'डेमो OTP:',
    job_details:        'काम की जानकारी',
    what_to_bring:      'क्या लाना है',
    money_note:         'शिफ़्ट के बाद पैसा सीधे आपके खाते में आएगा',
    you_will_earn:      'आपको मिलेगा',
    what_bring_items:   ['वैध पहचान पत्र','आरामदायक जूते','पानी की बोतल','आपका फ़ोन'],
    skills_title:       'मेरे कौशल',
    skills_sub:         'बताएँ कि आप क्या काम कर सकते हैं',
    edit_info:          'जानकारी बदलें',
    work_area:          'काम की जगह',
    languages_speak:    'मुझे आती है भाषा',
    save_changes:       'सेव करें',
    search_placeholder: 'नौकरी, कंपनी ढूंढें...',
    no_jobs_found:      'कोई नौकरी नहीं मिली',
    no_jobs_sub:        'अलग खोज या श्रेणी आज़माएँ',
    rate_job:           '⭐ इस काम को रेट करें',
    confirmed:          'पक्का',
    pending:            'बाकी है',
    completed:          'हो गया',
    jobs_done:          'काम किए',
    your_rating:        'आपकी रेटिंग',
    money_coming:       'पैसा आने वाला',
    results:            'परिणाम',
    all_jobs:           'सभी नौकरियाँ',
    date_when:          'कब',
    duration:           'कितना समय',
    pay_lbl:            'वेतन',
    distance:           'दूरी',
    slots:              'जगह',
    rating:             'रेटिंग',
    onb1_title:         'अपने पास काम ढूंढें',
    onb1_sub:           'घर से 5 किमी के अंदर सत्यापित काम देखें। अपने समय के अनुसार शिफ़्ट चुनें।',
    onb2_title:         '₹99–₹129 प्रति घंटा कमाएँ',
    onb2_sub:           'तय दर मिलेगी। कोई एजेंट कट नहीं। कोई छुपी फ़ीस नहीं। जो दिखे वही मिलेगा।',
    onb3_title:         'उसी दिन पैसा मिलेगा',
    onb3_sub:           'हर शिफ़्ट के बाद पैसा सीधे बैंक में आएगा। इंतज़ार नहीं करना।',
    onb4_title:         'सुरक्षित और सत्यापित काम ही',
    onb4_sub:           'हर नियोक्ता जाँचा हुआ है। हर काम असली है। आधार से सुरक्षा।',
    get_started:        'शुरू करें →',
    already_account:    'पहले से खाता है? लॉगिन करें',
    login_title:        'वापस आए',
    login_sub:          'जारी रखने के लिए अपना नंबर दर्ज करें',
    phone_label:        'मोबाइल नंबर',
    phone_placeholder:  '10 अंकों का नंबर दर्ज करें',
    password_label:     'पासवर्ड',
    password_placeholder:'पासवर्ड दर्ज करें',
    login_btn:          'लॉगिन करें',
    no_account:         'खाता नहीं है? पंजीकरण करें',
    register_title:     'खाता बनाएँ',
    register_sub:       'हज़ारों श्रमिकों के साथ रोज़ाना कमाएँ',
    name_label:         'पूरा नाम',
    name_placeholder:   'अपना पूरा नाम लिखें',
    city_label:         'आपका शहर',
    city_placeholder:   'जैसे मुंबई, दिल्ली, बेंगलुरु',
    lang_label:         'ऐप की भाषा',
    register_btn:       'खाता बनाएँ',
    have_account:       'पहले से खाता है? लॉगिन करें',
  },
}

/* ── Context ──────────────────────────────────── */
const LangCtx = createContext<{
  lang: Lang
  t: typeof T['en']
  setLang: (l: Lang) => void
}>({ lang: 'en', t: T.en, setLang: () => {} })

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const saved = localStorage.getItem('sw_lang') as Lang | null
    if (saved === 'en' || saved === 'hi') setLangState(saved)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('sw_lang', l)
  }

  return (
    <LangCtx.Provider value={{ lang, t: T[lang], setLang }}>
      {children}
    </LangCtx.Provider>
  )
}

export const useLang = () => useContext(LangCtx)
